---
version: '3'
Services:
  mydb:
    image: mysql:5
    environment:
      MYSQL_ROOT_PASSWORD: mahender
  mywordpress:
    image: wordpress
    ports:
      - 8888:80
    deploy:
      replicas: 3
...