---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    type: proxy
spec:
  containers:
    - name: mynginx
      image: nginx
      resources:
        requests:
          memory: "60mi"
          cpu: "250m"
        limits:
          memory: "120mi"
          cpu: "500m"
...