---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    author: mahender
spec:
  replicas: 2
  selector:
    matchLabels:
      author: mahender
  template:
    metadata:
      name: nginx-pod
      labels:
        author: mahender
   spec:
     containers:
       - name: mynginx
         image: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    author: mahender
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
  selector:
    author: mahender
...