---
apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  labels:
    name: postgres
    author: mahender
spec:
  containers:
    - name: mydb
      image: postgres
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_PASSWORD
          value: mahender
        - name: POSTGRES_DB
          value: mydb
        - name: POSTGRES_USER
          value: myuser
...