---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    author: mahender
    name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis
  template:
    metadata:
      name: redis-pod
      labels:
        name: redis
    spec:
      containers:
        - name: myredis
          image: redis
          ports:
            - containerPort: 6372
...
