---
wodpressUsername: admin
wordpressPassword: admin
wordpressEmail: mahender.penthala@gmail.com
wordpressFirstName: mahi
wordpressLastName: reddy
wordpressBlogName: mywordpress.com
services:
  type: LoadBalancer
...